version: 2

project_name: NoLets

builds:
  - id: darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: windows
    main: .
    goos:
      - windows
    goarch:
      - amd64
    goamd64:
      - v3
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [ 'tar.gz' ]
    files:
      - src: ./deploy/pushback.p8
        strip_parent: true
      - src: ./deploy/config.yaml
        strip_parent: true
      - LICENSE
      - README.md
      - README_EN.md

release:
  github:
    owner: sunvc
    name: NoLets
  name_template: "{{ .ProjectName }} {{ .Tag }}"
  mode: append
  header: |
    Example Download Links:
     curl -L -H "os:linux-amd" -o nolets.tar.gz https://wzs.app
  extra_files:
    - glob: ./deploy/pushback.p8
    - glob: ./deploy/config.yaml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'