version: 2

project_name: NoLets

builds:
  - id: darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: linux
    main: .
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goamd64:
      - v2
      - v3
      - v4
    goarm:
      - "5"
      - "6"
      - "7"
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: windows
    main: .
    goos:
      - windows
    goarch:
      - amd64
      - "386"
    goamd64:
      - v2
      - v3
      - v4
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: freebsd
    main: .
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: mipsle
    main: .
    goos:
      - linux
    goarch:
      - mipsle
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: mips
    main: .
    goos:
      - linux
    goarch:
      - mips
    gomips:
      - hardfloat
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0

  - id: mips64
    main: .
    goos:
      - linux
    goarch:
      - mips64
      - mips64le
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    flags:
      - -tags="sonic avx"
    env:
      - CGO_ENABLED=0
archives:
  - id: default
    formats: [ 'tar.gz' ]
    files:
      - pushback.p8
      - config.yaml
      - LICENSE
      - README.md
      - README_EN.md
      - README_KR.md
      - README_JP.md

release:
  github:
    owner: sunvc
    name: NoLets
  extra_files:
    - glob: ./pushback.p8
    - glob: ./config.yaml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
