services:
  NoLets:
    image: ghcr.io/sunvc/nolet:latest
    container_name: NoLets
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - NOLET_SIGN_KEY=
      - NOLET_AUTHS=